# Generated by Django 4.1.5 on 2025-08-20 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0048_alter_boat_ticket_inv_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('shop', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('agent', models.CharField(choices=[('Raju Barui', 'Raju Barui'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Pradip Dutta', 'Pradip Dutta'), ('Santanu', 'Santanu'), ('Anand', 'Anand'), ('Dibyendu', 'Dibyendu'), ('Kaka', 'Kaka'), ('Rabi', 'Rabi'), ('Suman Ghosh', 'Suman Ghosh')], max_length=25)),
                ('deposit_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('remarks', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='boat_ticket',
            name='agent',
            field=models.CharField(blank=True, choices=[('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Raju Barui', 'Raju Barui'), ('Deepraj Manna', 'Deepraj Manna'), ('Sanjay Banerjee', 'Sanjay Banerjee'), ('Arindam Prasad Mitra', 'Arindam Prasad Mitra'), ('Pradip Dutta', 'Pradip Dutta'), ('Suman Ghosh', 'Suman Ghosh')], max_length=25),
        ),
        migrations.AlterField(
            model_name='boat_ticket',
            name='pickup',
            field=models.CharField(choices=[('Pickup from Home', 'Pickup from Home'), ('Pickup from Retailer', 'Pickup from Retailer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='master',
            name='agent',
            field=models.CharField(choices=[('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Raju Barui', 'Raju Barui'), ('Deepraj Manna', 'Deepraj Manna'), ('Sanjay Banerjee', 'Sanjay Banerjee'), ('Arindam Prasad Mitra', 'Arindam Prasad Mitra'), ('Pradip Dutta', 'Pradip Dutta'), ('Suman Ghosh', 'Suman Ghosh')], max_length=25),
        ),
        migrations.AlterField(
            model_name='new_order',
            name='agent',
            field=models.CharField(choices=[('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Raju Barui', 'Raju Barui'), ('Deepraj Manna', 'Deepraj Manna'), ('Sanjay Banerjee', 'Sanjay Banerjee'), ('Arindam Prasad Mitra', 'Arindam Prasad Mitra'), ('Pradip Dutta', 'Pradip Dutta'), ('Suman Ghosh', 'Suman Ghosh')], max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='agent',
            field=models.CharField(choices=[('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Raju Barui', 'Raju Barui'), ('Deepraj Manna', 'Deepraj Manna'), ('Sanjay Banerjee', 'Sanjay Banerjee'), ('Arindam Prasad Mitra', 'Arindam Prasad Mitra'), ('Pradip Dutta', 'Pradip Dutta'), ('Suman Ghosh', 'Suman Ghosh')], max_length=25),
        ),
        migrations.AlterField(
            model_name='replacement',
            name='agent',
            field=models.CharField(choices=[('Tinku Das', 'Tinku Das'), ('Biswajit Sanyal', 'Biswajit Sanyal'), ('Rituraj Saran', 'Rituraj Saran'), ('Raju Barui', 'Raju Barui'), ('Deepraj Manna', 'Deepraj Manna'), ('Sanjay Banerjee', 'Sanjay Banerjee'), ('Arindam Prasad Mitra', 'Arindam Prasad Mitra'), ('Pradip Dutta', 'Pradip Dutta'), ('Suman Ghosh', 'Suman Ghosh')], max_length=25),
        ),
    ]
