# Generated by Django 4.1.4 on 2025-08-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chq_app', '0049_cash_alter_boat_ticket_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='mode1',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online/Cheque', 'Online/Cheque')], max_length=25),
        ),
        migrations.AlterField(
            model_name='cash',
            name='deposit_status',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
    ]
